import SpanEmoji from "@/components/SpanEmoji";
import type { LearnMoreItem } from "@/types";

export const LEARN_MORE_ITEMS: LearnMoreItem[] = [
    {
        id: "6ef75fbc",
        emojiImg: "emoji_u1f4b0.png",
        spanEmoji: <SpanEmoji value="&#x1F4B0;"/>,
        title: "Insurance vs Emergency Fund: Magkaiba Pero Magkasama",
        to: "/learn_more/emergency_fund_vs_insurance",
        image: "/learn_more/insurance_vs_emergency_fund.png",
    },
    {
        id: "dce97d0f",
        emojiImg: "emoji_u1f416.png",
        spanEmoji: <SpanEmoji value="&#x1F416;"/>,
        title: "The 3 Piggy Banks You Must Have",
        to: "/learn_more/the_3_piggy_banks_you_must_have",
        image: "/learn_more/the_3_piggy_banks_you_must_have.png",
    },
    {
        id: "27655ff9",
        emojiImg: "emoji_u1f3db.png",
        spanEmoji: <SpanEmoji value="&#x1F3DB;"/>,
        title: "The 4 Pillars of a Strong Wealth Protection",
        to: "/learn_more/the_4_pillars_of_a_strong_wealth_protection",
        image: "/learn_more/the_4_pillars_of_a_strong_wealth_protection.png",
    },
    {
        id: "07d05308",
        emojiImg: "emoji_u26a0.png",
        spanEmoji: <SpanEmoji value="&#x26a0;&#xFE0F;"/>,
        title: "The Hidden Costs of Critical Illness",
        to: "/learn_more/what_are_the_hidden_costs_of_critical_illness",
        image: "/learn_more/do_you_know_the_hidden_costs_of_critical_illness.png",
    },
    {
        id: "8321a958",
        emojiImg: "emoji_u1f4a1.png",
        spanEmoji: <SpanEmoji value="&#x1f4a1;"/>,
        title: "Do You Know the Actual Cost of Getting Seriously Ill in the Philippines?",
        to: "/learn_more/do_you_know_the_actual_cost_of_getting_seriously_ill_in_the_philippines",
        image: "/learn_more/do_you_know_the_actual_cost_of_getting_seriously_ill_in_the_philippines.png",
    },
    {
        id: "2c4bd14a",
        emojiImg: "emoji_u1fa7a.png",
        spanEmoji: <SpanEmoji value="&#x1fa7a;"/>,
        title: "Why Having PhilHealth Isn’t Enough — You Still Need Critical Illness Insurance",
        to: "/learn_more/why_having_philhealth_isnt_enough_you_still_need_critical_illness_insurance",
        image: "/learn_more/why_having_philhealth_isnt_enough_you_still_need_critical_illness_insurance.png",
    },
    {
        id: "cb2eea66",
        emojiImg: "emoji_u1fa7a.png",
        spanEmoji: <SpanEmoji value="&#x1fa7a;"/>,
        title: "Why Having an HMO Isn’t Enough — and Why You Still Need Critical Illness Insurance",
        to: "/learn_more/why_having_an_hmo_isnt_enough_you_still_need_critical_illness_insurance",
        image: "/learn_more/why_having_an_hmo_isnt_enough_you_still_need_critical_illness_insurance.png",
    },
    {
        id: "95441919",
        emojiImg: "emoji_u1f4aa.png",
        spanEmoji: <SpanEmoji value="&#x1F4AA;"/>,
        title: "4x Protection for Life’s Big Health Battles — Why FWD’s Critical Illness Plan is a Game Changer",
        to: "/learn_more/why_fwd_4x_critical_illness_protection_plan_is_a_game_changer",
        image: "/learn_more/why_fwd_4x_critical_illness_protection_plan_is_a_game_changer.png",
    },
    {
        id: "097249e8",
        emojiImg: "emoji_u1f4b0.png",
        spanEmoji: <SpanEmoji value="&#x1F4B0;"/>,
        title: "Insurance: The Smartest Way to Pass On Wealth — Tax-Free & Drama-Free",
        to: "/learn_more/the_smartest_way_to_pass_on_wealth",
        image: "/learn_more/the_smartest_way_to_pass_on_wealth.png",
    },
    {
        id: "abca9425",
        emojiImg: "emoji_u1f4a1.png",
        spanEmoji: <SpanEmoji value="&#x1F4A1;"/>,
        title: "Imagine getting paid every quarter — without working extra hours.",
        to: "/learn_more/how_i_earn_13k_pesos_passive_income_quarterly_from_my_fwd_investment_account",
        image: "/learn_more/my_insurance_with_quarterly_payout.png",
    },
    {
        id: "4f856144",
        emojiImg: "emoji_u1f4dd.png",
        spanEmoji: <SpanEmoji value="&#x1F4DD;"/>,
        title: "Checklist Before Getting an Insurance",
        to: "/learn_more/checklist_before_getting_an_insurance",
        image: "/learn_more/checklist_before_getting_an_insurance.png",
    },
    {
        id: "e752693b",
        emojiImg: "emoji_u1f9f1.png",
        spanEmoji: <SpanEmoji value="&#x1F9F1;"/>,
        title: "Build Your Financial Plan the Right Way: The Financial Needs Hierarchy",
        to: "/learn_more/financial_needs_hierarchy",
        image: "/learn_more/financial_needs_hierarchy.png",
    }
]
